#ifndef _M328PDEF_INC_
#define _M328PDEF_INC_
#pragma partinc 0
#pragma AVRPART ADMIN PART_NAME ATmega328P
#pragma AVRPART CORE CORE_VERSION V2E
#pragma AVRPART MEMORY PROG_FLASH 32768
#pragma AVRPART MEMORY EEPROM 1024
#pragma AVRPART MEMORY INT_SRAM SIZE 2048
#pragma AVRPART MEMORY INT_SRAM START_ADDR 0x100
#endif  /* _M328PDEF_INC_ */